export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in' },
  dashboard: {
    overview: '/dashboard',
    organization: '/dashboard/organization',
    users: '/dashboard/users',
    positions: '/dashboard/positions',
    zones: '/dashboard/zones',
    suppliers: '/dashboard/suppliers',
    categories: '/dashboard/categories',
    products: '/dashboard/products',
    productAnalytics: (id: string) => `/dashboard/products/${id}/analytics`,
    inventory: '/dashboard/inventory',
    inventoryZone: (id: string) => `/dashboard/inventory/${id}`,
    inventoryZoneHistory: (id: string) => `/dashboard/inventory/${id}/history`,
    inventorySession: (id: string) => `/dashboard/inventory/sessions/${id}`,
    myZones: '/dashboard/my-zones',
    receivings: '/dashboard/receivings',
    receivingsNew: '/dashboard/receivings/new',
    receiving: (id: string) => `/dashboard/receivings/${id}`,
    receivingEdit: (id: string) => `/dashboard/receivings/${id}/edit`,
    disposals: '/dashboard/disposals',
    disposalsNew: '/dashboard/disposals/new',
  },
} as const;
